//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanBroker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanBroker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group1_delegater_out.
        /// </summary>
        internal static string QueueNameBankDelegator {
            get {
                return ResourceManager.GetString("QueueNameBankDelegator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group1_bankfetcher_out.
        /// </summary>
        internal static string QueueNameBankFetcherOut {
            get {
                return ResourceManager.GetString("QueueNameBankFetcherOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group1_bank_out.
        /// </summary>
        internal static string QueueNameBankOut {
            get {
                return ResourceManager.GetString("QueueNameBankOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group1_creditbureau_out.
        /// </summary>
        internal static string QueueNameCreditScoreFetcherOut {
            get {
                return ResourceManager.GetString("QueueNameCreditScoreFetcherOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group1_loanbroker_in.
        /// </summary>
        internal static string QueueNameLoanBrokerIn {
            get {
                return ResourceManager.GetString("QueueNameLoanBrokerIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group1_loanbroker_out.
        /// </summary>
        internal static string QueueNameLoanBrokerOut {
            get {
                return ResourceManager.GetString("QueueNameLoanBrokerOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group1_normalizer_out.
        /// </summary>
        internal static string QueueNameNormalizerOut {
            get {
                return ResourceManager.GetString("QueueNameNormalizerOut", resourceCulture);
            }
        }
    }
}
