//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleBaseFetcher.RuleBaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RuleBaseService.RuleBaseServiceSoap")]
    public interface RuleBaseServiceSoap {
        
        // CODEGEN: Generating message contract since element name jSonRepOfBank from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddABank", ReplyAction="*")]
        RuleBaseFetcher.RuleBaseService.AddABankResponse AddABank(RuleBaseFetcher.RuleBaseService.AddABankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddABank", ReplyAction="*")]
        System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.AddABankResponse> AddABankAsync(RuleBaseFetcher.RuleBaseService.AddABankRequest request);
        
        // CODEGEN: Generating message contract since element name jSonRepOfBank from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveABank", ReplyAction="*")]
        RuleBaseFetcher.RuleBaseService.RemoveABankResponse RemoveABank(RuleBaseFetcher.RuleBaseService.RemoveABankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveABank", ReplyAction="*")]
        System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.RemoveABankResponse> RemoveABankAsync(RuleBaseFetcher.RuleBaseService.RemoveABankRequest request);
        
        // CODEGEN: Generating message contract since element name GetBanksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBanks", ReplyAction="*")]
        RuleBaseFetcher.RuleBaseService.GetBanksResponse GetBanks(RuleBaseFetcher.RuleBaseService.GetBanksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBanks", ReplyAction="*")]
        System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.GetBanksResponse> GetBanksAsync(RuleBaseFetcher.RuleBaseService.GetBanksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddABankRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddABank", Namespace="http://tempuri.org/", Order=0)]
        public RuleBaseFetcher.RuleBaseService.AddABankRequestBody Body;
        
        public AddABankRequest() {
        }
        
        public AddABankRequest(RuleBaseFetcher.RuleBaseService.AddABankRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddABankRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jSonRepOfBank;
        
        public AddABankRequestBody() {
        }
        
        public AddABankRequestBody(string jSonRepOfBank) {
            this.jSonRepOfBank = jSonRepOfBank;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddABankResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddABankResponse", Namespace="http://tempuri.org/", Order=0)]
        public RuleBaseFetcher.RuleBaseService.AddABankResponseBody Body;
        
        public AddABankResponse() {
        }
        
        public AddABankResponse(RuleBaseFetcher.RuleBaseService.AddABankResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddABankResponseBody {
        
        public AddABankResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveABankRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveABank", Namespace="http://tempuri.org/", Order=0)]
        public RuleBaseFetcher.RuleBaseService.RemoveABankRequestBody Body;
        
        public RemoveABankRequest() {
        }
        
        public RemoveABankRequest(RuleBaseFetcher.RuleBaseService.RemoveABankRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveABankRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jSonRepOfBank;
        
        public RemoveABankRequestBody() {
        }
        
        public RemoveABankRequestBody(string jSonRepOfBank) {
            this.jSonRepOfBank = jSonRepOfBank;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveABankResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveABankResponse", Namespace="http://tempuri.org/", Order=0)]
        public RuleBaseFetcher.RuleBaseService.RemoveABankResponseBody Body;
        
        public RemoveABankResponse() {
        }
        
        public RemoveABankResponse(RuleBaseFetcher.RuleBaseService.RemoveABankResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemoveABankResponseBody {
        
        public RemoveABankResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBanksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBanks", Namespace="http://tempuri.org/", Order=0)]
        public RuleBaseFetcher.RuleBaseService.GetBanksRequestBody Body;
        
        public GetBanksRequest() {
        }
        
        public GetBanksRequest(RuleBaseFetcher.RuleBaseService.GetBanksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBanksRequestBody {
        
        public GetBanksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBanksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBanksResponse", Namespace="http://tempuri.org/", Order=0)]
        public RuleBaseFetcher.RuleBaseService.GetBanksResponseBody Body;
        
        public GetBanksResponse() {
        }
        
        public GetBanksResponse(RuleBaseFetcher.RuleBaseService.GetBanksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBanksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RuleBaseFetcher.RuleBaseService.ArrayOfString GetBanksResult;
        
        public GetBanksResponseBody() {
        }
        
        public GetBanksResponseBody(RuleBaseFetcher.RuleBaseService.ArrayOfString GetBanksResult) {
            this.GetBanksResult = GetBanksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RuleBaseServiceSoapChannel : RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleBaseServiceSoapClient : System.ServiceModel.ClientBase<RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap>, RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap {
        
        public RuleBaseServiceSoapClient() {
        }
        
        public RuleBaseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleBaseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RuleBaseFetcher.RuleBaseService.AddABankResponse RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap.AddABank(RuleBaseFetcher.RuleBaseService.AddABankRequest request) {
            return base.Channel.AddABank(request);
        }
        
        public void AddABank(string jSonRepOfBank) {
            RuleBaseFetcher.RuleBaseService.AddABankRequest inValue = new RuleBaseFetcher.RuleBaseService.AddABankRequest();
            inValue.Body = new RuleBaseFetcher.RuleBaseService.AddABankRequestBody();
            inValue.Body.jSonRepOfBank = jSonRepOfBank;
            RuleBaseFetcher.RuleBaseService.AddABankResponse retVal = ((RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap)(this)).AddABank(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.AddABankResponse> RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap.AddABankAsync(RuleBaseFetcher.RuleBaseService.AddABankRequest request) {
            return base.Channel.AddABankAsync(request);
        }
        
        public System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.AddABankResponse> AddABankAsync(string jSonRepOfBank) {
            RuleBaseFetcher.RuleBaseService.AddABankRequest inValue = new RuleBaseFetcher.RuleBaseService.AddABankRequest();
            inValue.Body = new RuleBaseFetcher.RuleBaseService.AddABankRequestBody();
            inValue.Body.jSonRepOfBank = jSonRepOfBank;
            return ((RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap)(this)).AddABankAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RuleBaseFetcher.RuleBaseService.RemoveABankResponse RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap.RemoveABank(RuleBaseFetcher.RuleBaseService.RemoveABankRequest request) {
            return base.Channel.RemoveABank(request);
        }
        
        public void RemoveABank(string jSonRepOfBank) {
            RuleBaseFetcher.RuleBaseService.RemoveABankRequest inValue = new RuleBaseFetcher.RuleBaseService.RemoveABankRequest();
            inValue.Body = new RuleBaseFetcher.RuleBaseService.RemoveABankRequestBody();
            inValue.Body.jSonRepOfBank = jSonRepOfBank;
            RuleBaseFetcher.RuleBaseService.RemoveABankResponse retVal = ((RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap)(this)).RemoveABank(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.RemoveABankResponse> RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap.RemoveABankAsync(RuleBaseFetcher.RuleBaseService.RemoveABankRequest request) {
            return base.Channel.RemoveABankAsync(request);
        }
        
        public System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.RemoveABankResponse> RemoveABankAsync(string jSonRepOfBank) {
            RuleBaseFetcher.RuleBaseService.RemoveABankRequest inValue = new RuleBaseFetcher.RuleBaseService.RemoveABankRequest();
            inValue.Body = new RuleBaseFetcher.RuleBaseService.RemoveABankRequestBody();
            inValue.Body.jSonRepOfBank = jSonRepOfBank;
            return ((RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap)(this)).RemoveABankAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RuleBaseFetcher.RuleBaseService.GetBanksResponse RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap.GetBanks(RuleBaseFetcher.RuleBaseService.GetBanksRequest request) {
            return base.Channel.GetBanks(request);
        }
        
        public RuleBaseFetcher.RuleBaseService.ArrayOfString GetBanks() {
            RuleBaseFetcher.RuleBaseService.GetBanksRequest inValue = new RuleBaseFetcher.RuleBaseService.GetBanksRequest();
            inValue.Body = new RuleBaseFetcher.RuleBaseService.GetBanksRequestBody();
            RuleBaseFetcher.RuleBaseService.GetBanksResponse retVal = ((RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap)(this)).GetBanks(inValue);
            return retVal.Body.GetBanksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.GetBanksResponse> RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap.GetBanksAsync(RuleBaseFetcher.RuleBaseService.GetBanksRequest request) {
            return base.Channel.GetBanksAsync(request);
        }
        
        public System.Threading.Tasks.Task<RuleBaseFetcher.RuleBaseService.GetBanksResponse> GetBanksAsync() {
            RuleBaseFetcher.RuleBaseService.GetBanksRequest inValue = new RuleBaseFetcher.RuleBaseService.GetBanksRequest();
            inValue.Body = new RuleBaseFetcher.RuleBaseService.GetBanksRequestBody();
            return ((RuleBaseFetcher.RuleBaseService.RuleBaseServiceSoap)(this)).GetBanksAsync(inValue);
        }
    }
}
