//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RuleBaseFetcher.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RuleBaseSoap", Namespace="http://WorldOfRule.org/")]
    public partial class RuleBase : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddABankOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveABankOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBanksOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RuleBase() {
            this.Url = global::RuleBaseFetcher.Properties.Settings.Default.RuleBaseFetcher_localhost_RuleBase;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddABankCompletedEventHandler AddABankCompleted;
        
        /// <remarks/>
        public event RemoveABankCompletedEventHandler RemoveABankCompleted;
        
        /// <remarks/>
        public event GetBanksCompletedEventHandler GetBanksCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WorldOfRule.org/AddABank", RequestNamespace="http://WorldOfRule.org/", ResponseNamespace="http://WorldOfRule.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddABank(Bank bank) {
            this.Invoke("AddABank", new object[] {
                        bank});
        }
        
        /// <remarks/>
        public void AddABankAsync(Bank bank) {
            this.AddABankAsync(bank, null);
        }
        
        /// <remarks/>
        public void AddABankAsync(Bank bank, object userState) {
            if ((this.AddABankOperationCompleted == null)) {
                this.AddABankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddABankOperationCompleted);
            }
            this.InvokeAsync("AddABank", new object[] {
                        bank}, this.AddABankOperationCompleted, userState);
        }
        
        private void OnAddABankOperationCompleted(object arg) {
            if ((this.AddABankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddABankCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WorldOfRule.org/RemoveABank", RequestNamespace="http://WorldOfRule.org/", ResponseNamespace="http://WorldOfRule.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveABank(Bank bank) {
            this.Invoke("RemoveABank", new object[] {
                        bank});
        }
        
        /// <remarks/>
        public void RemoveABankAsync(Bank bank) {
            this.RemoveABankAsync(bank, null);
        }
        
        /// <remarks/>
        public void RemoveABankAsync(Bank bank, object userState) {
            if ((this.RemoveABankOperationCompleted == null)) {
                this.RemoveABankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveABankOperationCompleted);
            }
            this.InvokeAsync("RemoveABank", new object[] {
                        bank}, this.RemoveABankOperationCompleted, userState);
        }
        
        private void OnRemoveABankOperationCompleted(object arg) {
            if ((this.RemoveABankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveABankCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WorldOfRule.org/GetBanks", RequestNamespace="http://WorldOfRule.org/", ResponseNamespace="http://WorldOfRule.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Bank[] GetBanks(decimal amount, int creditScore, int duration, string ssn) {
            object[] results = this.Invoke("GetBanks", new object[] {
                        amount,
                        creditScore,
                        duration,
                        ssn});
            return ((Bank[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBanksAsync(decimal amount, int creditScore, int duration, string ssn) {
            this.GetBanksAsync(amount, creditScore, duration, ssn, null);
        }
        
        /// <remarks/>
        public void GetBanksAsync(decimal amount, int creditScore, int duration, string ssn, object userState) {
            if ((this.GetBanksOperationCompleted == null)) {
                this.GetBanksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBanksOperationCompleted);
            }
            this.InvokeAsync("GetBanks", new object[] {
                        amount,
                        creditScore,
                        duration,
                        ssn}, this.GetBanksOperationCompleted, userState);
        }
        
        private void OnGetBanksOperationCompleted(object arg) {
            if ((this.GetBanksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBanksCompleted(this, new GetBanksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WorldOfRule.org/")]
    public partial class Bank {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AddABankCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void RemoveABankCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetBanksCompletedEventHandler(object sender, GetBanksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBanksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBanksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bank[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bank[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591